# Generated by Django 2.0 on 2018-04-24 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GoodsCategotyBrand',
            new_name='GoodsCategoryBrand',
        ),
    ]
